#!/bin/bash

set -e  # Exit immediately if any command fails

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

# zsh
echo "Setting up .zshrc"
rm -rf ~/.zshrc
ln -s "$SCRIPT_DIR/.zshrc" ~/.zshrc

# git
echo "Setting up .gitconfig and .gitignore"
rm -rf ~/.gitconfig ~/.gitignore
ln -s "$SCRIPT_DIR/git/.gitconfig" ~/.gitconfig
ln -s "$SCRIPT_DIR/git/.gitignore" ~/.gitignore

echo "Setup complete!"